[platformio]
default_envs = photo_frame_gs_02

[env:photo_frame_gs_02]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.psram_size = 8MB
board_build.arduino.loop_stack_size = 49152
board_upload.flash_size = 16MB
board_upload.maximum_ram_size = 524288
board_upload.maximum_size = 2097152
upload_port = COM4
upload_protocol = esptool
upload_speed = 921600
monitor_port = COM4
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-std=c++17
	-DBOARD_HAS_PSRAM
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DCONFIG_SPIRAM_USE_MALLOC
	-DCONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
	-DCONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=16384
	-DCONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_EPD_DISPLAY_TYPE_ED047TC1
	-DCONFIG_EPD_BOARD_REVISION_LILYGO_T5_47_PLUS
extra_scripts = scripts/firmware_sha.py
lib_deps = 
#	xinyuan-lilygo/LilyGoEPD47@^0.3.0
# bitbank2/JPEGDEC@^1.8.4
# xreef/SimpleFTPServer@^3.0.1
# arduino-libraries/ArduinoHttpClient@^0.6.1
test_ignore = *

[env:esp32_test]
extends = env:photo_frame_gs_02
test_framework = unity
test_ignore = 
lib_deps = 
  ${env:photo_frame_gs_02.lib_deps}
  throwtheswitch/Unity@^2.6.0
build_src_filter = +<*> -<Main.cpp>

[env:native]
platform = windows_x86
test_framework = unity
build_flags = -std=c++17
lib_deps = throwtheswitch/Unity@^2.6.0
build_src_filter = -<*>
test_ignore = test_ESP32